// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A flow to generate SEO tags (keywords) from a topic.
 *
 * - generateSeoTags - A function that handles the SEO tag generation process.
 * - GenerateSeoTagsInput - The input type for the generateSeoTags function.
 * - GenerateSeoTagsOutput - The return type for the generateSeoTags function.
 */

import {ai, configureUserGenkit} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateSeoTagsInputSchema = z.object({
  topic: z.string().describe('The topic to generate SEO tags for.'),
  apiKey: z.string().describe("The user's Gemini API key."),
});
export type GenerateSeoTagsInput = z.infer<typeof GenerateSeoTagsInputSchema>;

const GenerateSeoTagsOutputSchema = z.object({
  tags: z.array(z.string()).describe('An array of SEO tags (keywords) related to the topic.'),
});
export type GenerateSeoTagsOutput = z.infer<typeof GenerateSeoTagsOutputSchema>;

export async function generateSeoTags(input: GenerateSeoTagsInput): Promise<GenerateSeoTagsOutput> {
  configureUserGenkit(input.apiKey);
  return generateSeoTagsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateSeoTagsPrompt',
  input: {schema: GenerateSeoTagsInputSchema},
  output: {schema: GenerateSeoTagsOutputSchema},
  prompt: `You are an expert in SEO and keyword generation.

  Given the following topic, generate a list of SEO tags (keywords) that can be used to help a video rank higher in search results.

  Topic: {{{topic}}}

  Ensure the tags are relevant, diverse, and include both short-tail and long-tail keywords.
  Return the tags as a JSON array of strings.
  `,
});

const generateSeoTagsFlow = ai.defineFlow(
  {
    name: 'generateSeoTagsFlow',
    inputSchema: GenerateSeoTagsInputSchema,
    outputSchema: GenerateSeoTagsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
