import { config } from 'dotenv';
config();

import '@/ai/flows/generate-youtube-script.ts';
import '@/ai/flows/generate-seo-tags.ts';
import '@/ai/flows/generate-youtube-title.ts';
import '@/ai/flows/generate-youtube-description.ts';
import '@/ai/flows/generate-instagram-story-flow.ts';
import '@/ai/flows/generate-thumbnail-image.ts';
import '@/ai/flows/generate-caption.ts';
import '@/ai/flows/generate-video-ideas.ts';
import '@/ai/flows/generate-hashtag.ts';
import '@/ai/flows/improve-script.ts';
import '@/ai/flows/generate-reel-script.ts';
import '@/ai/flows/generate-carousel-slides.ts';
import '@/ai/flows/convert-video-to-script.ts';
import '@/ai/flows/generate-voiceover.ts';
import '@/ai/flows/discover-trending-reels.ts';
import '@/ai/flows/generate-chapters.ts';
import '@/ai/flows/generate-content-strategy.ts';
import '@/ai/flows/generate-shorts-from-script.ts';
import '@/ai/flows/generate-feature-video.ts';
import '@/ai/flows/generate-launch-campaign.ts';
import '@/ai/flows/find-viral-video-ideas.ts';
import '@/ai/flows/generate-shorts-from-script.ts';
